# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
array = np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
array = np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
array=np.arange(10,50,1)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [6]:
array=np.arange(10,52,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
x = np.identity(3).reshape(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
a= np.random.normal(0,1)
a

1.45437684611967

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
a= np.random

#### Create the following matrix:

array([[0.47325185, 0.31687143, 0.92315798, 0.00944664, 0.60830481,
        0.47149244, 0.79730795, 0.72197131, 0.84899411, 0.01795184],
       [0.57900727, 0.34508023, 0.48016543, 0.99348081, 0.06871019,
        0.31279884, 0.55701429, 0.98209127, 0.51928253, 0.92712081],
       [0.62565429, 0.80846004, 0.72829608, 0.34980847, 0.2327374 ,
        0.47676367, 0.38464416, 0.5483618 , 0.63090987, 0.36734357],
       [0.47504607, 0.6957894 , 0.10041094, 0.83642747, 0.109461  ,
        0.37350456, 0.18693862, 0.83277221, 0.27106925, 0.39778378],
       [0.77510687, 0.78144895, 0.35545704, 0.23139187, 0.87181658,
        0.46630382, 0.31662621, 0.2948518 , 0.52938676, 0.97693867],
       [0.04279191, 0.7529686 , 0.27601624, 0.037062  , 0.49163982,
        0.08637015, 0.17704648, 0.02366608, 0.19145927, 0.38069567],
       [0.25340951, 0.8950335 , 0.23507032, 0.18247659, 0.57591731,
        0.97841964, 0.89265674, 0.48002304, 0.40070118, 0.50849625],
       [0.6112385 , 0.29325072, 0.0759372

#### Create an array of 20 linearly spaced points between 0 and 1:

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [20]:
A =np.arange(1,26).reshape(5,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
A[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
A[3,4]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
A[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
A[4,:]

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
A[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [30]:
A.sum()

325

#### Get the standard deviation of the values in mat

In [31]:
A.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [35]:
A.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!